### ISSUE TITLE
Bug: Unhandled Exception: ClientException with SocketException

### ISSUE THREAD

**Issue by marcglasberg** [celest-dev/celest#80]
I just upgraded to Celest 0.3.1, and now I'm getting this:

```
E/flutter (16110): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 10.0.2.2, port = 56032, uri=http://10.0.2.2:7780/stocks/read-updated-stock-price
E/flutter (16110): #0      IOClient.send (package:http/src/io_client.dart:154:7)
E/flutter (16110): <asynchronous suspension>
E/flutter (16110): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter (16110): <asynchronous suspension>
E/flutter (16110): #2      CelestFunctionsStocks.readUpdatedStockPrice (package:celest_backend/src/client/functions.dart:358:23)
E/flutter (16110): <asynchronous suspension>
E/flutter (16110): #3      RealDao.startListeningToStockPriceUpdates.<anonymous closure> (package:mobile_app_flutter_celest/client/infra/dao/real_dao.dart:64:25)
E/flutter (16110): <asynchronous suspension>
```

**Comment by dnys1** [comment]
On it!

**Comment by dnys1** [comment]
@marcglasberg I believe this should be fixed as well now.
